# Generated by Django 3.2.8 on 2021-11-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0008_webpush_add_edge'),
    ]

    operations = [
		migrations.RemoveField(
			model_name='gcmdevice',
			name='device_id',
		),
		migrations.AddField(
			model_name='gcmdevice',
			name='device_id',
			field=models.CharField(blank=True, db_index=True, null=True, max_length=255, verbose_name='Device ID'),
		)
    ]
